### ISSUE TITLE
Could you possibly make available a demo .pltraw file

### ISSUE THREAD

**Issue by b1tc0der** [dfeneyrou/palanteer#14]
I think it'd be handy for evaluation purposes.

**Comment by dfeneyrou** [comment]
The canonical pltraw example file can be created with ```./bin/testprogram collect -f``` (if you built the viewer, you should also have this testprogram).
The output is a ~11MB file "example_record.pltraw" that can be imported into the viewer.

I agree however that this part is not well documented.
Do you confirm that a more explicit process description would be enough?

Storing such generated example output inside the GIT repo would double its total size, so I am not sure that it is worth it.

**Comment by b1tc0der** [comment]
My apologies, I totally missed the test program and that it creates a demo .pltraw file.
That's definitely enough and not worth committing to the repository.
This project is amazing; keep up the good work!
