### ISSUE TITLE
plgScopeDyn() with USE_PL=0 throws build errors

### ISSUE THREAD

**Issue by Lnsrini** [dfeneyrou/palanteer#15]
Hello,

Thank you for the Palanteer project. It has made my life a lot easier. Cheers to you guys!

I face the following issue whenbuilding with Palanteer deactivated.
I wish to deactivate Palanteer when my program is built in 'Release'.
I noticed an issue I have with plgScopeDyn() when USE_PL is  set to '0'. 

This is my code **(USE_PL = 0)**:

```
#define PL_IMPLEMENTATION 1
#define PL_GROUP_TEST 1
#include "palanteer.h"
.
.
.
[[maybe_unused]] auto text = "testFunc";
plgScopeDyn(TEST, text);
```

When I compile this code with clang, I get the following error:
`use of undeclared identifier 'TEST'`

The rest of the pl[g]***Dyn() variant functions (`plgFunction()`, `plgLockScopeState()`, do not seem to cause build errors.

**Comment by dfeneyrou** [comment]
Hello,
Thanks for the reporting!
Indeed, this API was missing in the section defining the empty API when the instrumentation API is disabled.
All the group APIs are now included inside the test program, so that they are covered by the tests.
