### ISSUE TITLE
[Mac OS port] Potential issues with keyboard modifier state

### ISSUE THREAD

**Issue by jceipek** [dfeneyrou/palanteer#19]
In my MacOS port, I've been noticing issues where the application didn't realize I was holding down certain modifier keys.
I believe the cause is that the modifier state isn't being appropriately synchronized here: https://github.com/dfeneyrou/palanteer/blob/main/server/viewer/vwPlatform.cpp#L642-L718

Note that the `kms` parameter is ignored in many of the functions in the file, which can lead to these imgui fields not being synchronized to the keyboard state correctly:

```
io.KeyCtrl
io.KeyShift
io.KeyAlt  
io.KeySuper
```

I also haven't been able to determine which `osHandler->event*` function would be best to call when responding to the `NSEventTypeFlagsChanged` event type on macOS. See https://github.com/ocornut/imgui/blob/0b8a2470743f89d19ab2d5920606434b604b529e/backends/imgui_impl_osx.mm#L342-L345 for how it is handled in the Dear ImGui example.

**Comment by dfeneyrou** [comment]
See answer in #18 .
I cannot help for Mac OS related questions because I have no such environment at hand nor experience with it.
However, [Dear Imgui](https://github.com/ocornut/imgui) contains valuable information for this kind of project in its various examples.

**Comment by jceipek** [comment]
@dfeneyrou What are your thoughts on adding this? https://github.com/dfeneyrou/palanteer/pull/21/files#diff-2d88bc2cf5369b76a592e61c044242925375802ffdcbcbf8440711355359fe76R695-R707

And do you think it makes sense to add something like
```
     io.KeyCtrl  = kms.ctrl;
     io.KeyShift = kms.shift;
     io.KeyAlt   = kms.alt;
     io.KeySuper = kms.sys;
```

to all of the `vwPlatform.cpp` functions that accept `kms` parameters but ignore them?

**Comment by dfeneyrou** [comment]
Closing because too old, and I do not have MacOS to work on it.
