### ISSUE TITLE
How to start service (so thread/fiber registration works) but not start recording yet?

### ISSUE THREAD

**Issue by BrodyHiggerson** [dfeneyrou/palanteer#26]
I've been trying the fiber integration as per your helpful Gist from a while back (https://gist.github.com/dfeneyrou/8f8aa2956dcb32e0860665c610d7bb2f).

I was following my usage pattern of Optick, where I didn't start profiling from the beginning but instead triggered it via a debug menu. However, my FTL Task Scheduler is created at the beginning, and its creation invokes the callbacks shown in the above Gist. Because of this, the calls to e.g. plDeclareVirtualThread take place before the call to plInitAndStart, and so in the profiler itself none of that information is shown.

Am I able to somehow start up the service at the beginning so that these registrations are accepted, but not start any kind of recording / transmission to the Palanteer application until later? I know there's PL_MODE_INACTIVE, but as far as I can see, the mode can't be changed after the init call?

I'll have to try calling plInitAndStart at game start, creating my scheduler and having the FTL callbacks fire, then immediately calling plStopAndUninit, and then calling init again later when I want to actually profile. Bit messy though and not sure if it works right.

EDIT: Looks like init-stop-init isn't the solution; not surprised.

![image](https://user-images.githubusercontent.com/7245990/141684242-67505d72-6c3e-4fcc-b3fd-ea382b793dcd.png)

**Comment by dfeneyrou** [comment]
Hi Brody,
Indeed, the current implementation expects that all thread declarations are done after the event service initialization.
I agree that it is not user friendly (it is a software constraint) and is also prevent your use case which is a totally valid one.

Supporting your use case implies to store all declared thread names (virtual or not) and send the already known ones at connection time, then both continue storing the next declarations while sending them directly to the server.
This way would allow also seamless cycles of starting/stopping the recording.

**Comment by dfeneyrou** [comment]
Do not hesitate to open more issues if it does not work as expected for your use case!
