### ISSUE TITLE
Possible race condition leading to access to NULL pointer

### ISSUE THREAD

**Issue by gpascualg** [dfeneyrou/palanteer#30]
This might have been partly due to overflow, as I saw buffer saturation previously. Either case, the race condition seems to be there.

On commit: fd6a6a3e0914eae579216ab43793bd5dc62c53cf
Compiler: `gcc 9.3.0` with `-g -O0 --std=c++20`
You can hopefully reproduce it using the exact code, though I haven't exhaustively tested it (should work on x86_64, but who knows, it's way too hacky right now).
https://github.com/NetPunkSoftware/Fibers/commit/405d493cf4199a0b34a966b86a6a51def8417f0f

It happens about 3 out of every 5 executions.

------------------------------------------

Now, into what I believe is a race condition. See the following two stack traces:

Thread 1:

```
plPriv::hashString(const char * s, int maxCharQty) (/home/guillem/Github/Fibers/build/_deps/palanteer-src/c++/palanteer.h:1460)
plPriv::collectEvents(bool doForce) (/home/guillem/Github/Fibers/build/_deps/palanteer-src/c++/palanteer.h:3485)
plPriv::transmitToServer() (/home/guillem/Github/Fibers/build/_deps/palanteer-src/c++/palanteer.h:3874)
std::__invoke_impl<void, void (*)()>(void (*&&)(void) __f) (/usr/include/c++/11/bits/invoke.h:61)
std::__invoke<void (*)()>(void (*&&)(void) __fn) (/usr/include/c++/11/bits/invoke.h:96)
std::thread::_Invoker<std::tuple<void (*)()> >::_M_invoke<0ul>(std::thread::_Invoker<std::tuple<void (*)()> > * const this) (/usr/include/c++/11/bits/std_thread.h:253)
std::thread::_Invoker<std::tuple<void (*)()> >::operator()(std::thread::_Invoker<std::tuple<void (*)()> > * const this) (/usr/include/c++/11/bits/std_thread.h:260)
std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)()> > >::_M_run(std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)()> > > * const this) (/usr/include/c++/11/bits/std_thread.h:211)
libstdc++.so.6![Unknown/Just-In-Time compiled code] (Unknown Source:0)
libpthread.so.0!start_thread(void * arg) (/home/build/YPKG/root/glibc/build/glibc.git/nptl/pthread_create.c:481)
libc.so.6!clone() (/home/build/YPKG/root/glibc/build-avx2/glibc.git/sysdeps/unix/sysv/linux/x86_64/clone.S:95)
```

Particularly `plPriv::collectEvents` at `palanteer-src/c++/palanteer.h:3485`. The current even being iterated, `src`, points to `0x7ffff70af990`.

Other variables of possible interest (at `collectEvents`):

```
evtIdx = 12901
eventQty = 20036
globalCtx.prevBankAndIndex = 20036
```

--------------------------------

Now, Thread 2:

```
plPriv::eventLogBase(uint32_t bi, plPriv::hashStr_t filenameHash_, plPriv::hashStr_t nameHash_, const char * filename_, const char * name_, int lineNbr_, int flags_) (/home/guillem/Github/Fibers/build/_deps/palanteer-src/c++/palanteer.h:1545)
plPriv::eventLogRaw(plPriv::hashStr_t filenameHash_, plPriv::hashStr_t nameHash_, const char * filename_, const char * name_, int lineNbr_, bool doSkipOverflowCheck_, int flags_, plPriv::bigRawData_t v) (/home/guillem/Github/Fibers/build/_deps/palanteer-src/c++/palanteer.h:1565)
plPriv::TimedScope::~TimedScope(plPriv::TimedScope * const this) (/home/guillem/Github/Fibers/build/_deps/palanteer-src/c++/palanteer.h:1825)
np::fiber_pool_base::worker_thread(np::fiber_pool_base * const this, uint8_t idx) (/home/guillem/Github/Fibers/src/pool/fiber_pool.cpp:171)
std::__invoke_impl<void, void (np::fiber_pool_base::*)(unsigned char) noexcept, np::fiber_pool<np::detail::default_fiber_pool_traits>*, int>(std::__invoke_memfun_deref, void (np::fiber_pool_base::*&&)(unsigned char) noexcept, np::fiber_pool<np::detail::default_fiber_pool_traits>*&&, int&&)(void (np::fiber_pool_base::*&&)(np::fiber_pool_base * const, unsigned char) __f, np::fiber_pool<np::detail::default_fiber_pool_traits> *&& __t) (/usr/include/c++/11/bits/invoke.h:74)
std::__invoke<void (np::fiber_pool_base::*)(unsigned char) noexcept, np::fiber_pool<np::detail::default_fiber_pool_traits>*, int>(void (np::fiber_pool_base::*&&)(unsigned char) noexcept, np::fiber_pool<np::detail::default_fiber_pool_traits>*&&, int&&)(void (np::fiber_pool_base::*&&)(np::fiber_pool_base * const, unsigned char) __fn) (/usr/include/c++/11/bits/invoke.h:96)
std::thread::_Invoker<std::tuple<void (np::fiber_pool_base::*)(unsigned char) noexcept, np::fiber_pool<np::detail::default_fiber_pool_traits>*, int> >::_M_invoke<0ul, 1ul, 2ul>(std::_Index_tuple<0ul, 1ul, 2ul>)(std::thread::_Invoker<std::tuple<void (np::fiber_pool_base::*)(unsigned char) noexcept, np::fiber_pool<np::detail::default_fiber_pool_traits>*, int> > * const this) (/usr/include/c++/11/bits/std_thread.h:253)
std::thread::_Invoker<std::tuple<void (np::fiber_pool_base::*)(unsigned char) noexcept, np::fiber_pool<np::detail::default_fiber_pool_traits>*, int> >::operator()()(std::thread::_Invoker<std::tuple<void (np::fiber_pool_base::*)(unsigned char) noexcept, np::fiber_pool<np::detail::default_fiber_pool_traits>*, int> > * const this) (/usr/include/c++/11/bits/std_thread.h:260)
std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (np::fiber_pool_base::*)(unsigned char) noexcept, np::fiber_pool<np::detail::default_fiber_pool_traits>*, int> > >::_M_run()(std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (np::fiber_pool_base::*)(unsigned char) noexcept, np::fiber_pool<np::detail::default_fiber_pool_traits>*, int> > > * const this) (/usr/include/c++/11/bits/std_thread.h:211)
libstdc++.so.6![Unknown/Just-In-Time compiled code] (Unknown Source:0)
libpthread.so.0!start_thread(void * arg) (/home/build/YPKG/root/glibc/build/glibc.git/nptl/pthread_create.c:481)
libc.so.6!clone() (/home/build/YPKG/root/glibc/build-avx2/glibc.git/sysdeps/unix/sysv/linux/x86_64/clone.S:95)
```

The last call, `plPriv::eventLogBase`, at `palanteer-src/c++/palanteer.h:1545`, is writing an event. Uppon inspection, `e` has the same address `0x7ffff70af990`.  It has crashed short of writing the string itself, which would have been the next line. At the moment of the crash, `e.nameHash == 0` and `e.name == 0`.

Other variables of possible interest (at `eventLogBase`):

```
bi = 12901
```

---------------------------------------------

If this is caused due to me going well beyond the acceptable buffer size, maybe we could introduce some assertion during debug, so that it triggers instead of causing UB.

Otherwise, I see two ways of going over this:

1) Adding a local `ready` atomic to each event, so that the consumer must spin/yield until it is flagged by the producer.

2) Using two pointers to the buffer, so that one points to the last valid position (ie. written and valid) and the another one points to the last writable position (ie. free and not being used).

**Comment by Freddyoo8** [comment]
@pascual thread 2 has exceed the buffer size and will lead to something
else.

Lemme get toy desk and I'll send you the thread I worked on. Thank you

**Comment by dfeneyrou** [comment]
I could not reproduce the issue on my machine, by running `fibers_test` (tried 20 times, also directly in a file to see if it changes the dynamic).
Maybe it is because my PC only 2 cores so the conditions are not met... (I also used boost 1.74, due to Debian 11, but I do not think this would change anything)

> If this is caused due to me going well beyond the acceptable buffer size...

There is already a mechanism to prevent the events being written beyong the buffer size. The `eventCheckOverflow()` function is called after each logging and waits (by yielding) for the next collection buffer swap if the buffer size is reached (there is a margin of 1 extra event per thread).
When this happens, the thread which logged is blocked until the collection happens and frees some space, and a marker "SATURATION" is added to the event stream.

It looks that there is a flaw somewhere in this mechanism (at least in your use case).  I will continue to investigate.

**Comment by dfeneyrou** [comment]
As a temporary workaround so that you are not blocked by this issue if it is linked to a problem in the saturation handling, you can increase the collection buffer size.
By default, the value is 5 MB and is configurable, if you have some available RAM.

Example, to be placed before the `palanteer.h` include which implements the service (so in main.cpp):
```
#define PL_IMPL_COLLECTION_BUFFER_BYTE_QTY 20000000
```

**Comment by dfeneyrou** [comment]
I reproduced some instabilities, and there are some flaws in the mechanisms.
Working on it.

**Comment by dfeneyrou** [comment]
The last commit should solve this issue.
If you have some time to confirm it, that would be great!

**Comment by gpascualg** [comment]
Sorry for not getting back sooner on the previous messages, I have been having a really busy week at work.

I confirm that after 100 executions on d92f0f303183787b3315c7b55dba4734603d7729 it hasn't crashed once. Thank you for the hard work on this amazing tool!

**Comment by dfeneyrou** [comment]
Great news, thanks for your support and feedback!
