### ISSUE TITLE
unexpected app shutdown

### ISSUE THREAD

**Issue by italiks** [dfeneyrou/palanteer#37]
I have a big profiling data file > 1gb. After loading application hangs and closes.
Reproducibility 100%

[https://transfer.pcloud.com/download.html?code=5ZELnbVZ6rcgA5EfxkFZLzoUZkVrHCBRnHrLtwaNHIHgEQm8jksKy](profile data)

**Comment by dfeneyrou** [comment]
Thanks for your file, I downloaded it and saw some message about corruption after importing, but no hangs nor crash.
Which OS do you use? Windows or Linux (I tested on Linux)?
Which version of the palanteer executable did you use? Built by you from the top of tree of the sources, or you used the already built one from Windows release 0.6, or latest built?

Anyway, the pltraw is enough to analyse the issue, I will look at it ASAP.

**Comment by italiks** [comment]
built from the latest sources from the main branch on Windows 10. For build used msvc 2022.
If you need any further information please let me know.

Tried to load in debug build to get crash dump or some other information (assert), but got the same unexpected quit.
If needed can show a video

**Comment by dfeneyrou** [comment]
I have done several fixes thanks to your file:
- when the maximum thread quantity was reached, the GUI was not properly handling it and could lead to a crash
- the O(N^2) configuration loading was unsuitable with big number of drawable item path (more than 1 million), leading to very slow (more like a kind of hanging) when trying to live display or loading.
