### ISSUE TITLE
Installing on aarch64, eg Nvidia Jetson

### ISSUE THREAD

**Issue by samiamlabs** [dfeneyrou/palanteer#45]
Hi!

I'm trying to build this great project on an Nvidia Jetson Orin NX but I'm having some issues.

I get an error indicating that it can't find `Python.h`, but I do in fact have a `Python.h` under `/usr/include/python3.8/`.
I tried setting export C_INCLUDE_PATH=/usr/include/python3.8:$C_INCLUDE_PATH but that did not help

```bash
palanteer/server/scripting/palanteer_scripting/_cextension/pyPalanteerScript.cpp:26:10: fatal error: Python.h: No such file or directory
   26 | #include "Python.h"
```

The graphical palanteer tool seems to build and run!

Installing with pip3 for the python stuff did not work, as it failed building the wheel.

Any suggestions on how to proceed?

**Comment by dfeneyrou** [comment]
Sorry for late answer...
I checked that the build is ok on my side with python3.8, you probably forgot to install the python dev package on your machine.  This package provides the internal C interface for Python.
So just try: ```sudo apt install python3.8-dev```
